# Levenshtein distance with two variables (and implicit ordering)

PREFIX gama: <http://gama-gateway.eu/schema/>
SELECT * WHERE {
  ?work  rdf:type gama:Work;
         gama:work_title ?title.

  _:w gama:work_title ?t2. FILTER gama:match("alfred", ?t2).
 
  FILTER gama:levenshtein(?title, ?t2, 4)
} limit 10
