# Similar media: number of similarities per manifestation 

PREFIX gama: <http://gama-gateway.eu/schema/>
SELECT
  ?manif_uri
  count(?shotid) as ?count
WHERE {

  ?manif_uri a gama:Manifestation.
  ?similar_manif a gama:Manifestation.
  FILTER gama:similar_media( ?manif_uri, ?shotid, ?similar_manif)

  # uncomment this if you want to restrict the query to a known manifestation URI
  # FILTER (?manif_uri = <MANIFESTATION_URI_COMES_HERE> )
}
GROUP BY ?manif_uri
ORDER BY DESC(?count)
LIMIT 100
